name: $(BuildDefinitionName).$(Build.SourceBranchName).$(Rev:.r)

trigger: none

pr:
- master

jobs:
  - job: Janus
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        Janus:
          stage.name: 'Janus'
          container.name: 'ivadim/fruitnanny-janus'
        GStreamer:
          stage.name: 'GStreamer'
          container.name: 'ivadim/fruitnanny-gstreamer'
        Fruitnanny:
          stage.name: 'Fruitnanny'
          container.name: 'ivadim/fruitnanny-app'
      maxParallel: 3

    steps:
    - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset
      docker build . -f docker/janus/Dockerfile -t $(container.name)
      displayName: 'Build $(stage.name) Container'