name: $(major).$(minor).$(patch)

trigger:
- master

pr: none

variables:
  major: 1
  minor: 0
  patch: $[counter('versioncounter', 1)]

jobs:
  - job: Janus
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        Janus:
          stage.name: 'Janus'
          container.name: 'ivadim/fruitnanny-janus'
        GStreamer:
          stage.name: 'GStreamer'
          container.name: 'ivadim/fruitnanny-gstreamer'
        Fruitnanny:
          stage.name: 'Fruitnanny'
          container.name: 'ivadim/fruitnanny-app'
      maxParallel: 3
    steps:
      - script: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
          docker build . -f docker/janus/Dockerfile -t $(container.name)
        displayName: 'Build $(stage.name) Container'

      - script: |
          docker image save ivadim/fruitnanny-janus -o $(Build.ArtifactStagingDirectory)/fruitnanny-app-$(Build.BuildNumber).tgz
        displayName: 'Export $(stage.name) Container Image'

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: $(stage.name)