# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- script: |
    docker run --rm --privileged multiarch/qemu-user-static:register --reset
    docker build . -f docker/fruitnanny/Dockerfile -t ivadim/fruitnanny-app
    docker build . -f docker/gstreamer/Dockerfile -t ivadim/fruitnanny-gstreamer
    docker build . -f docker/janus/Dockerfile -t ivadim/fruitnanny-janus
  displayName: 'Build fruitnanny docker images'
